modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Wheeple"
description="Contentcraft adds features and mechanics that expand on Minecraft while keeping the vanilla feel!"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="libtooltips"
type="required"
versionRange="[1.4,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="patchouli"
type="required"
versionRange="[1.21.1-92-NEOFORGE,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="terrablender"
type="required"
versionRange="[1.21.1-4.1.0.8,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[1.21.1-neoforge-19.27.0.340,)"
ordering="NONE"
side="BOTH"
